name: Archive Transport Data

on:
  schedule:
    #We only have to update 3 URLs per day, so we run it at different times to avoid conflicts with other jobs
    # 1am, 9am, 5pm
    - cron: '0 1,9,18 * * *'
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install puppeteer

    - name: Archive URL
      env:
        WA_USERNAME: ${{ secrets.WA_USERNAME }}
        WA_PASSWORD: ${{ secrets.WA_PASSWORD }}
      run: ./archive_transport.sh

